-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.admins
(
    id bigint NOT NULL DEFAULT nextval('admins_id_seq'::regclass),
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    email character varying(150) COLLATE pg_catalog."default",
    nama character varying(150) COLLATE pg_catalog."default",
    password text COLLATE pg_catalog."default",
    CONSTRAINT admins_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.chairs
(
    kode character varying(3) COLLATE pg_catalog."default" NOT NULL,
    harga bigint,
    id bigint NOT NULL DEFAULT nextval('chairs_id_seq'::regclass),
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    CONSTRAINT chairs_pkey PRIMARY KEY (kode)
);

CREATE TABLE IF NOT EXISTS public.film_genres
(
    genre_id bigint NOT NULL,
    film_id bigint NOT NULL,
    CONSTRAINT film_genres_pkey PRIMARY KEY (genre_id, film_id)
);

CREATE TABLE IF NOT EXISTS public.films
(
    id bigint NOT NULL DEFAULT nextval('films_id_seq'::regclass),
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    judul character varying(150) COLLATE pg_catalog."default",
    poster character varying(150) COLLATE pg_catalog."default",
    deskripsi text COLLATE pg_catalog."default",
    trailer character varying(150) COLLATE pg_catalog."default",
    rating numeric,
    tangal_rilis date,
    CONSTRAINT films_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.foods
(
    id bigint NOT NULL DEFAULT nextval('foods_id_seq'::regclass),
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    nama character varying(50) COLLATE pg_catalog."default",
    harga bigint,
    CONSTRAINT foods_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.genres
(
    id bigint NOT NULL DEFAULT nextval('genres_id_seq'::regclass),
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    nama character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT genres_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.order_chairs
(
    order_id bigint NOT NULL,
    chair_kode character varying(3) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT order_chairs_pkey PRIMARY KEY (order_id, chair_kode)
);

CREATE TABLE IF NOT EXISTS public.orders
(
    id bigint NOT NULL DEFAULT nextval('orders_id_seq'::regclass),
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    total bigint,
    user_id bigint,
    showschedule_id bigint,
    CONSTRAINT orders_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.show_schedules
(
    id bigint NOT NULL DEFAULT nextval('show_schedules_id_seq'::regclass),
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    tanggal character varying(30) COLLATE pg_catalog."default",
    jam character varying(30) COLLATE pg_catalog."default",
    film_id bigint,
    studio_id bigint,
    CONSTRAINT show_schedules_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.studios
(
    id bigint NOT NULL DEFAULT nextval('studios_id_seq'::regclass),
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    nama character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT studios_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id bigint NOT NULL DEFAULT nextval('users_id_seq'::regclass),
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    email character varying(150) COLLATE pg_catalog."default",
    nama character varying(150) COLLATE pg_catalog."default",
    password text COLLATE pg_catalog."default",
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.film_genres
    ADD CONSTRAINT fk_film_genres_genre FOREIGN KEY (genre_id)
    REFERENCES public.genres (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.order_chairs
    ADD CONSTRAINT fk_order_chairs_chair FOREIGN KEY (chair_kode)
    REFERENCES public.chairs (kode) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.order_chairs
    ADD CONSTRAINT fk_order_chairs_order FOREIGN KEY (order_id)
    REFERENCES public.orders (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT fk_orders_show_schedule FOREIGN KEY (showschedule_id)
    REFERENCES public.show_schedules (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT fk_orders_user FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.show_schedules
    ADD CONSTRAINT fk_show_schedules_film FOREIGN KEY (film_id)
    REFERENCES public.films (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.show_schedules
    ADD CONSTRAINT fk_show_schedules_studio FOREIGN KEY (studio_id)
    REFERENCES public.studios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;